repos:
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: ["--profile", "black", "--force-single-line-imports"]
- repo: https://github.com/myint/autoflake
  rev: v1.4
  hooks:
  - id: autoflake
    args: ["--recursive", "--remove-all-unused-imports", "--remove-unused-variables", "--in-place"]
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.6.2
  hooks:
    - id: prettier
      types_or: [css, javascript, html]
      exclude: static/*
- repo: https://github.com/commitizen-tools/commitizen
  rev: master
  hooks:
    - id: commitizen
      stages: [commit-msg]
